TESTER_ROLE_NAME = "tester"
PATIENT_ROLE_NAME = "surveyUser"
ADMIN_ROLE_NAME = "admin"
SUPER_USER_ROLE_NAME = "super"
PATIENT_ADMINISTRATOR = "Patient Self Administered"
#HOSTNAME="54.173.213.213"
HOSTNAME="localhost:8000"
MAX_HOURS_VALID_SESSION = 24