# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-04 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('stopTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntologyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('questionId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('questionAnswerId', models.IntegerField()),
                ('questionAnswerRangeLower', models.IntegerField(blank=True, null=True)),
                ('questionAnswerRangeUpper', models.IntegerField(blank=True, null=True)),
                ('requiredFlag', models.NullBooleanField()),
                ('phiFlag', models.NullBooleanField()),
                ('pictureURL', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('choiceOntology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choiceOntology', to='smellSurvey.Ontology')),
                ('questionAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.QuestionAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(blank=True, null=True)),
                ('answerText', models.CharField(blank=True, max_length=256, null=True)),
                ('answerText2', models.CharField(blank=True, max_length=256, null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Administration')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.QuestionAnswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerTimeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('questionAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.QuestionAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('version', models.IntegerField()),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('isSuperUser', models.BooleanField()),
                ('isAdministrator', models.BooleanField()),
                ('isPatient', models.BooleanField()),
                ('isTester', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('sequence', models.IntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UPIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upinId', models.IntegerField()),
                ('sessionId', models.CharField(blank=True, max_length=512, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Study')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('surveyuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smellSurvey.SurveyUser')),
                ('allowedSites', models.ManyToManyField(to='smellSurvey.Site')),
                ('allowedStudies', models.ManyToManyField(to='smellSurvey.Study')),
            ],
            bases=('smellSurvey.surveyuser',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('surveyuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smellSurvey.SurveyUser')),
                ('surveyLink', models.CharField(max_length=256)),
                ('isDeleted', models.BooleanField()),
                ('defaultAdministrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultAdministrator', to='smellSurvey.Administrator')),
                ('defaultSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultSite', to='smellSurvey.Site')),
                ('defaultStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultStudy', to='smellSurvey.Study')),
                ('studies', models.ManyToManyField(to='smellSurvey.Study')),
            ],
            bases=('smellSurvey.surveyuser',),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Role'),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='questionAnswerDataType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.QuestionAnswerDataType'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='questionAnswerOntology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerOntologyClassSubClass', to='smellSurvey.Ontology'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='questionAnswerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.QuestionAnswerType'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='smellSurvey.QuestionAnswer'),
        ),
        migrations.AddField(
            model_name='question',
            name='ontologyClassSubClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionOntologyClassSubClass', to='smellSurvey.Ontology'),
        ),
        migrations.AddField(
            model_name='question',
            name='ontologyIndividual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionOntologyIndividual', to='smellSurvey.Ontology'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentQuestion', to='smellSurvey.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='parentAnswer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentAnswer', to='smellSurvey.QuestionAnswer'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Section'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontologyType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.OntologyType'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='smellSurvey.Ontology'),
        ),
        migrations.AddField(
            model_name='administration',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Questionnaire'),
        ),
        migrations.AddField(
            model_name='administration',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Site'),
        ),
        migrations.AddField(
            model_name='administration',
            name='upin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.UPIN'),
        ),
        migrations.AddField(
            model_name='upin',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smellSurvey.Patient'),
        ),
        migrations.AddField(
            model_name='administration',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to='smellSurvey.Administrator'),
        ),
    ]
